#!/bin/sh
# Télécharge les photos du site dans images/ (licence Pexels).
# Ensuite, activez le bloc « version locale » à la fin de images.css.
set -e
mkdir -p images

echo "→ vitrine.jpg  (Breads In A Bakery)"
curl -sSL -o "images/vitrine.jpg" "https://images.pexels.com/photos/3341067/pexels-photo-3341067.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ viennoiseries.jpg  (Croissant with a Price Tag in a Bakery)"
curl -sSL -o "images/viennoiseries.jpg" "https://images.pexels.com/photos/19803486/pexels-photo-19803486.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ pains.jpg  (Sourdough bread with burnt crust on table)"
curl -sSL -o "images/pains.jpg" "https://images.pexels.com/photos/6605201/pexels-photo-6605201.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ sandwichs.jpg  (A Baguette Sandwich on a Plate)"
curl -sSL -o "images/sandwichs.jpg" "https://images.pexels.com/photos/17498978/pexels-photo-17498978.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ cafe.jpg  (Cup of Coffee and Bagel)"
curl -sSL -o "images/cafe.jpg" "https://images.pexels.com/photos/17180513/pexels-photo-17180513.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ boutique.jpg  (Charming Nevis Bakery in Fort William)"
curl -sSL -o "images/boutique.jpg" "https://images.pexels.com/photos/31083446/pexels-photo-31083446.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ fournee.jpg  (Tray with Croissants for Baking)"
curl -sSL -o "images/fournee.jpg" "https://images.pexels.com/photos/19987146/pexels-photo-19987146.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ comptoir.jpg  (Cookies on Display)"
curl -sSL -o "images/comptoir.jpg" "https://images.pexels.com/photos/16637678/pexels-photo-16637678.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ croissant.jpg  (Croissant, Flowers and Bread)"
curl -sSL -o "images/croissant.jpg" "https://images.pexels.com/photos/20410181/pexels-photo-20410181.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ pain-chocolat.jpg  (Man Basting Croissants before Baking)"
curl -sSL -o "images/pain-chocolat.jpg" "https://images.pexels.com/photos/7965949/pexels-photo-7965949.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ brioche.jpg  (A Pastry Chef Making Croissants)"
curl -sSL -o "images/brioche.jpg" "https://images.pexels.com/photos/7966375/pexels-photo-7966375.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ baguette.jpg  (Close-up of a Loaf of Bread)"
curl -sSL -o "images/baguette.jpg" "https://images.pexels.com/photos/15301249/pexels-photo-15301249.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ campagne.jpg  (Slices of bread on cutting board)"
curl -sSL -o "images/campagne.jpg" "https://images.pexels.com/photos/6605208/pexels-photo-6605208.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ sandwich.jpg  (Delicious Tomato and Lettuce Baguette Sandwich)"
curl -sSL -o "images/sandwich.jpg" "https://images.pexels.com/photos/34593400/pexels-photo-34593400.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ salade.jpg  (Vegetable Salad in a Bowl)"
curl -sSL -o "images/salade.jpg" "https://images.pexels.com/photos/7660426/pexels-photo-7660426.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ soupe.jpg  (Soup and Bread Served in a Restaurant)"
curl -sSL -o "images/soupe.jpg" "https://images.pexels.com/photos/19503784/pexels-photo-19503784.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ cafe-formule.jpg  (A Cup of Coffee and a Toasted Sandwich on a Tray)"
curl -sSL -o "images/cafe-formule.jpg" "https://images.pexels.com/photos/6612776/pexels-photo-6612776.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "→ patisserie.jpg  (Baked Cookies and Pastry on the Plate)"
curl -sSL -o "images/patisserie.jpg" "https://images.pexels.com/photos/10819659/pexels-photo-10819659.jpeg?auto=compress&cs=tinysrgb&w=1400"
echo "Terminé : $(ls images/*.jpg | wc -l) photos dans images/"
